# Session #1  Homework

This notebook represent the #1 Homework of ML-Zoomcamp 

### Import packages

In [1]:
import pandas as pd
import numpy as np

### Get the data

In [2]:

url_data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
df = pd.read_csv(url_data)


### Inspect the data

In [3]:
df.sample(5)

Make       Model  Year                Engine Fuel Type  \
11397      Suzuki      Vitara  2002                regular unleaded   
6732       Nissan      Maxima  2016  premium unleaded (recommended)   
7216   Volkswagen  New Beetle  2010                regular unleaded   
547          FIAT         500  2015  premium unleaded (recommended)   
3187     Cadillac         CT6  2017     premium unleaded (required)   

       Engine HP  Engine Cylinders Transmission Type      Driven_Wheels  \
11397      127.0               4.0         AUTOMATIC   four wheel drive   
6732       300.0               6.0         AUTOMATIC  front wheel drive   
7216       150.0               5.0         AUTOMATIC  front wheel drive   
547        160.0               4.0            MANUAL  front wheel drive   
3187       404.0               6.0         AUTOMATIC    all wheel drive   

       Number of Doors                      Market Category Vehicle Size  \
11397              2.0                                  NaN      Compact   
6732               4.0                     High-Performance      Midsize   
7216               2.0                            Hatchback      Compact   
547                2.0  Hatchback,Factory Tuner,Performance      Compact   
3187               4.0              Luxury,High-Performance        Large   

         Vehicle Style  highway MPG  city mpg  Popularity   MSRP  
11397  Convertible SUV           23        20         481  17999  
6732             Sedan           30        22        2009  39960  
7216     2dr Hatchback           29        20         873  20390  
547      2dr Hatchback           34        28         819  22495  
3187             Sedan           26        18        1624  87495

## Question 1

What's the version of NumPy that you installed?

In [4]:
print(np.__version__)

1.23.2


## Question 2

How many records are in the dataset?

In [5]:
print(len(df))

11914


## Question 3

3. Who are the most frequent car manufacturers (top-3) according to the dataset?

In [6]:
df.value_counts(['Make']).sort_values(ascending=False).head(3)

Make      
Chevrolet     1123
Ford           881
Volkswagen     809
dtype: int64

## Question 4

4) What's the number of unique Audi car models in the dataset?

In [7]:
len(df[df['Make']=='Audi']['Model'].unique())

34

## Question 5

How many columns in the dataset have missing values?

In [8]:
(df.isnull().sum()!=0).sum()

5

## Question 6
* Find the median value of "Engine Cylinders" column in the dataset.
* Next, calculate the most frequent value of the same "Engine Cylinders".
* Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
* Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?

1. Find the median "Engine Cylinders"

In [9]:
df['Engine Cylinders'].median()

6.0

2. Most frequent value in "Engine Cylinders"

In [10]:
most_frequent_engine_cylinder= df['Engine Cylinders'].mode().iloc[0]
most_frequent_engine_cylinder

4.0

3 y 4) Fill N/A values with the most frequent value in "Engine Cylinders" and calculate the median value of "Engine Cylinders" once again.

In [11]:
df['Engine Cylinders'].fillna(most_frequent_engine_cylinder).median()

6.0

Has it changed?

**R:** No, filling in missing fields with the mode of 'Engine Cylinders' does not affect the median value.


### Question 7
* Select all the "Lotus" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the first element of w?

1) Select all the "Lotus" cars from the dataset.

In [12]:

df_lotus= df[df['Make']=='Lotus']
df_lotus.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

2) Select only columns "Engine HP", "Engine Cylinders".

In [13]:
df_lotus= df_lotus[['Engine HP',"Engine Cylinders"]]

3) drop all duplicated rows

In [14]:
df_lotus =df_lotus.drop_duplicates()

4) Get the underlying NumPy array

In [15]:
X = df_lotus.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

5) Compute matrix-matrix multiplication between the transpose of X and X

In [16]:
XTX = X.T@X
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

6) Invert XTX.

In [17]:
Invert_XTX = np.linalg.inv(XTX)

7) Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

In [18]:
y= np.array([[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]]).T

8) Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [19]:
w = Invert_XTX@X.T@y
w

array([[  4.59494481],
       [-63.56432501]])

9) First element of w

What's the value of the first element of w?

In [20]:
w[0]

array([4.59494481])